version: "3.8"

services:
  scholten:
    container_name: ${PROJECT_NAME}
    hostname: ${PROJECT_NAME}
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
