# build environment
FROM node:13.12.0-alpine as build

ARG REACT_APP_GOOGLE_API

WORKDIR /usr/app

ENV NODE_PATH=src
ENV REACT_APP_GOOGLE_API=$REACT_APP_GOOGLE_API
ENV PATH=/usr/app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm ci --only=production

COPY . .

RUN npm run build

# production environment
FROM nginx:stable-alpine

COPY --from=build /usr/app/build /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]