version: "3.8"

services:
  scholten:
    container_name: ${PROJECT_NAME}
    hostname: ${PROJECT_NAME}
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      # Use ./keys to test ssl locally, given you generate the keys 
      # and alter the config to use them
      # - ./keys:/etc/letsencrypt/live/yardsign.scholten4iowa.com/
    ports:
      - 80:80
      - 443:443
